# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "wojak.pink"
email: "wojakpink@protonmail.com"
description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wojak.pink" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "WojakDotPink"
github_username:  "wojakpink"

# Cryptocurrency Addresses
address_eth_donate: "0x7e86AFC6769f099508786DC1BA6c4A064C73E3c8"

# Text Variables
donation_link_text: "don't click this unless you want to give me free money"

# Permalink Variables
permalink_donate: "/donate/index.html"

# Build settings
remote_theme: "wojakpink/theme.wojak.pink@main"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
